name: build-image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: get source code
      uses: actions/checkout@v2
      with:
        path: 'source'

    - name: get and build sqlite3 3.31
      run: |
        cd $GITHUB_WORKSPACE
        mkdir sqlite3
        cd sqlite3
        wget https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
        tar xvf sqlite-autoconf-3310100.tar.gz
        cd sqlite-autoconf-3310100
        ./configure
        make
        sudo make install
        cd /usr/lib/x86_64-linux-gnu
        #sudo ln -sf /usr/local/lib/libsqlite3.so
        #sudo ln -sf /usr/local/lib/libsqlite3.so.0
        #cd /usr/include
        #sudo ln -sf ../local/include/sqlite3.h
    
    - name: build proftpd with mod proxy
      run: |
        cd $GITHUB_WORKSPACE
        mkdir proftpd
        cd proftpd
        wget https://github.com/proftpd/proftpd/archive/v1.3.7a.tar.gz
        tar xvf v1.3.7a.tar.gz
        wget https://github.com/Castaglia/proftpd-mod_proxy/archive/v0.5.tar.gz
        cd proftpd-1.3.7a/contrib/
        tar xvf ../../v0.5.tar.gz
        mv proftpd-mod_proxy-0.5/ mod_proxy
        cd ..
        ./configure --with-modules=mod_proxy
        make
        sudo make install
        cp /usr/local/sbin/proftpd $GITHUB_WORKSPACE/source/
        cp /usr/local/libexec/mod_proxy* $GITHUB_WORKSPACE/source/
    
    - name: build docker image
      run: |
        cd $GITHUB_WORKSPACE/source
        ls -l
        docker build -t proftpd .
      
